apiVersion: v1
kind: ConfigMap
metadata:
  name: vp-config
data:
  NODE_ENV: "development"
  PORT: "4000"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  AWS_REGION: "us-east-1"
  S3_RAW_BUCKET: "video-transcoder-raw-praveen"
  S3_PROCESSED_BUCKET: "video-transcoder-processed-praveen"
  CLOUDFRONT_DOMAIN: "d26bqkv291jafs.cloudfront.net"
  FFMPEG_PATH: "/usr/bin/ffmpeg"
  FFPROBE_PATH: "/usr/bin/ffprobe"
  PRESIGNED_URL_EXPIRY: "3000"
