apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: transcoder-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: transcoder-worker
  maxReplicaCount: 10
  pollingInterval: 5
  cooldownPeriod: 30
  minReplicaCount: 1
  triggers:
    - type: redis
      metadata:
        address: redis.default.svc.cluster.local:6379  
        listName: bull:video-transcode:wait
        listLength: "1"
# listlength refer to number of jobs handled by pods 